import Link from 'next/link';

export default function Footer() {
  return (
    <footer className="bg-ink-black text-newsprint mt-16">
      <div className="max-w-newspaper mx-auto px-4 md:px-8 py-12">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-8 mb-10">
          {/* Sections */}
          <div>
            <h4 className="font-masthead text-sm uppercase tracking-widest mb-4 text-accent-gold">Sections</h4>
            <ul className="space-y-2 font-ui text-sm">
              <li><Link href="/section/tech/" className="hover:text-accent-gold transition-colors">Technology</Link></li>
              <li><Link href="/section/business/" className="hover:text-accent-gold transition-colors">Business</Link></li>
              <li><Link href="/section/security/" className="hover:text-accent-gold transition-colors">Security</Link></li>
              <li><Link href="/section/culture/" className="hover:text-accent-gold transition-colors">Culture</Link></li>
            </ul>
          </div>
          
          {/* Company */}
          <div>
            <h4 className="font-masthead text-sm uppercase tracking-widest mb-4 text-accent-gold">Company</h4>
            <ul className="space-y-2 font-ui text-sm">
              <li><Link href="#about" className="hover:text-accent-gold transition-colors">About Us</Link></li>
              <li><Link href="#careers" className="hover:text-accent-gold transition-colors">Careers</Link></li>
              <li><Link href="#contact" className="hover:text-accent-gold transition-colors">Contact</Link></li>
              <li><Link href="#press" className="hover:text-accent-gold transition-colors">Press</Link></li>
            </ul>
          </div>
          
          {/* Subscribe */}
          <div>
            <h4 className="font-masthead text-sm uppercase tracking-widest mb-4 text-accent-gold">Subscribe</h4>
            <ul className="space-y-2 font-ui text-sm">
              <li><Link href="#newsletter" className="hover:text-accent-gold transition-colors">Newsletter</Link></li>
              <li><Link href="#rss" className="hover:text-accent-gold transition-colors">RSS Feed</Link></li>
              <li><Link href="#podcast" className="hover:text-accent-gold transition-colors">Podcast</Link></li>
            </ul>
          </div>
          
          {/* Legal */}
          <div>
            <h4 className="font-masthead text-sm uppercase tracking-widest mb-4 text-accent-gold">Legal</h4>
            <ul className="space-y-2 font-ui text-sm">
              <li><Link href="#privacy" className="hover:text-accent-gold transition-colors">Privacy Policy</Link></li>
              <li><Link href="#terms" className="hover:text-accent-gold transition-colors">Terms of Service</Link></li>
              <li><Link href="#cookies" className="hover:text-accent-gold transition-colors">Cookie Policy</Link></li>
            </ul>
          </div>
        </div>
        
        {/* Bottom */}
        <div className="text-center pt-8 border-t border-white/10">
          <p className="font-tagline italic text-lg mb-2">&ldquo;The only way to do great work is to ship it.&rdquo;</p>
          <p className="font-ui text-xs opacity-60">
            GITSHIP NEWS · Powered by the Newsroom Swarm · Articles generated by autonomous AI agents
          </p>
        </div>
      </div>
    </footer>
  );
}
